// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

// Teacher-Student relationships
export const teacherStudents = {
  1: [ // John Doe's students
    { id: 1, name: "Sarah Johnson", studentId: "STU001", class: "5A" },
    { id: 2, name: "Mike Wilson", studentId: "STU002", class: "5A" },
    { id: 3, name: "Emma Davis", studentId: "STU003", class: "5A" },
    { id: 4, name: "James Brown", studentId: "STU004", class: "5A" },
    { id: 5, name: "Lisa Garcia", studentId: "STU005", class: "5A" }
  ],
  2: [ // Jane Doe's students
    { id: 6, name: "Anna Martinez", studentId: "STU006", class: "4B" },
    { id: 7, name: "David Lee", studentId: "STU007", class: "4B" },
    { id: 8, name: "Sophie Taylor", studentId: "STU008", class: "4B" }
  ]
};

// Attendance records
export const attendanceData = [
  {
    id: 1,
    date: "2025-01-15",
    teacherId: 1,
    present: [1, 2, 4, 5],
    absent: [3]
  },
  {
    id: 2,
    date: "2025-01-14",
    teacherId: 1,
    present: [1, 2, 3, 5],
    absent: [4]
  },
  {
    id: 3,
    date: "2025-01-15",
    teacherId: 2,
    present: [6, 7],
    absent: [8]
  }
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-07-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-07-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-07-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-07-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-07-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-07-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-07-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-07-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-07-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-07-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-04-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-06-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-06-11",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-05-04",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-08-10",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-03-29",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-06-13",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-09-12",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-05-09",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-04-15",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// Grade data for students
export const studentGrades = {
  1: [ // Student ID 1 grades
    { subject: "Math", semester1: 8.5, semester2: 9.1 },
    { subject: "English", semester1: 9.2, semester2: 8.8 },
    { subject: "Physics", semester1: 7.8, semester2: 8.5 },
    { subject: "Chemistry", semester1: 9.5, semester2: 9.8 },
    { subject: "Biology", semester1: 8.9, semester2: 9.3 }
  ],
  2: [ // Student ID 2 grades
    { subject: "Math", semester1: 7.5, semester2: 8.1 },
    { subject: "English", semester1: 8.2, semester2: 7.8 },
    { subject: "Physics", semester1: 6.8, semester2: 7.5 },
    { subject: "Chemistry", semester1: 8.5, semester2: 8.8 },
    { subject: "Biology", semester1: 7.9, semester2: 8.3 }
  ]
};

// Teacher class grades (average of all students in their class)
export const teacherClassGrades = {
  1: [ // Teacher ID 1 class grades
    { studentId: 1, studentName: "John Doe", semester1: 8.5, semester2: 9.1 },
    { studentId: 2, studentName: "Jane Doe", semester1: 7.5, semester2: 8.1 },
    { studentId: 3, studentName: "Mike Geller", semester1: 9.2, semester2: 8.8 },
    { studentId: 4, studentName: "Jay French", semester1: 7.8, semester2: 8.5 },
    { studentId: 5, studentName: "Jane Smith", semester1: 8.9, semester2: 9.3 }
  ]
};

// Calendar events for next week starting Monday September 30, 2025
export const calendarEvents = [
  {
    id: 1,
    title: "Math - Algebra",
    subject: "Math",
    teacher: "John Doe",
    class: "5A",
    room: "Room 101",
    allDay: false,
    start: new Date(2025, 8, 30, 8, 0),
    end: new Date(2025, 8, 30, 9, 0),
  },  
  {
    id: 2,
    title: "English - Literature",
    subject: "English",
    teacher: "Jane Smith",
    class: "5A",
    room: "Room 102",
    allDay: false,
    start: new Date(2025, 8, 30, 9, 0),
    end: new Date(2025, 8, 30, 10, 0),
  },
  {
    id: 3,
    title: "Biology - Cell Structure",
    subject: "Biology",
    teacher: "Mike Geller",
    class: "5A",
    room: "Lab 201",
    allDay: false,
    start: new Date(2025, 8, 30, 10, 0),
    end: new Date(2025, 8, 30, 11, 0),
  },
  {
    id: 4,
    title: "Chemistry - Organic",
    subject: "Chemistry",
    teacher: "Anna Santiago",
    class: "5A",
    room: "Lab 202",
    allDay: false,
    start: new Date(2025, 8, 30, 13, 0),
    end: new Date(2025, 8, 30, 14, 0),
  },
  {
    id: 5,
    title: "History - World War II",
    subject: "History",
    teacher: "Jay French",
    class: "5A",
    room: "Room 103",
    allDay: false,
    start: new Date(2025, 8, 30, 14, 0),
    end: new Date(2025, 8, 30, 15, 0),
  },
  {
    id: 6,
    title: "English - Grammar",
    subject: "English",
    teacher: "Jane Smith",
    class: "5A",
    room: "Room 102",
    allDay: false,
    start: new Date(2025, 9, 1, 9, 0),
    end: new Date(2025, 9, 1, 10, 0),
  },
  {
    id: 7,
    title: "Biology - Genetics",
    subject: "Biology",
    teacher: "Mike Geller",
    class: "5A",
    room: "Lab 201",
    allDay: false,
    start: new Date(2025, 9, 1, 10, 0),
    end: new Date(2025, 9, 1, 11, 0),
  },
  {
    id: 8,
    title: "Physics - Mechanics",
    subject: "Physics",
    teacher: "Allen Black",
    class: "5A",
    room: "Lab 203",
    allDay: false,
    start: new Date(2025, 9, 1, 11, 0),
    end: new Date(2025, 9, 1, 12, 0),
  },
  {
    id: 9,
    title: "Chemistry - Reactions",
    subject: "Chemistry",
    teacher: "Anna Santiago",
    class: "5A",
    room: "Lab 202",
    allDay: false,
    start: new Date(2025, 9, 1, 13, 0),
    end: new Date(2025, 9, 1, 14, 0),
  },
  {
    id: 10,
    title: "History - Ancient Rome",
    subject: "History",
    teacher: "Jay French",
    class: "5A",
    room: "Room 103",
    allDay: false,
    start: new Date(2025, 9, 1, 14, 0),
    end: new Date(2025, 9, 1, 15, 0),
  },
  {
    id: 11,
    title: "Physics - Thermodynamics",
    subject: "Physics",
    teacher: "Allen Black",
    class: "5A",
    room: "Lab 203",
    allDay: false,
    start: new Date(2025, 9, 2, 11, 0),
    end: new Date(2025, 9, 2, 12, 0),
  },
  {
    id: 12,
    title: "History - Renaissance",
    subject: "History",
    teacher: "Jay French",
    class: "5A",
    room: "Room 103",
    allDay: false,
    start: new Date(2025, 9, 2, 14, 0),
    end: new Date(2025, 9, 2, 15, 0),
  },
  {
    id: 13,
    title: "Math - Geometry",
    subject: "Math",
    teacher: "John Doe",
    class: "5A",
    room: "Room 101",
    allDay: false,
    start: new Date(2025, 9, 2, 8, 0),
    end: new Date(2025, 9, 2, 9, 0),
  },
  {
    id: 14,
    title: "Biology - Ecology",
    subject: "Biology",
    teacher: "Mike Geller",
    class: "5A",
    room: "Lab 201",
    allDay: false,
    start: new Date(2025, 9, 2, 10, 0),
    end: new Date(2025, 9, 2, 11, 0),
  },
  {
    id: 15,
    title: "Chemistry - Lab Work",
    subject: "Chemistry",
    teacher: "Anna Santiago",
    class: "5A",
    room: "Lab 202",
    allDay: false,
    start: new Date(2025, 9, 2, 13, 0),
    end: new Date(2025, 9, 2, 14, 0),
  },
  {
    id: 16,
    title: "History - Modern Era",
    subject: "History",
    teacher: "Jay French",
    class: "5A",
    room: "Room 103",
    allDay: false,
    start: new Date(2025, 9, 3, 14, 0),
    end: new Date(2025, 9, 3, 15, 0),
  },
  {
    id: 17,
    title: "English - Poetry",
    subject: "English",
    teacher: "Jane Smith",
    class: "5A",
    room: "Room 102",
    allDay: false,
    start: new Date(2025, 9, 3, 9, 0),
    end: new Date(2025, 9, 3, 10, 0),
  },
  {
    id: 18,
    title: "Biology - Evolution",
    subject: "Biology",
    teacher: "Mike Geller",
    class: "5A",
    room: "Lab 201",
    allDay: false,
    start: new Date(2025, 9, 3, 10, 0),
    end: new Date(2025, 9, 3, 11, 0),
  },
  {
    id: 19,
    title: "Physics - Electricity",
    subject: "Physics",
    teacher: "Allen Black",
    class: "5A",
    room: "Lab 203",
    allDay: false,
    start: new Date(2025, 9, 3, 11, 0),
    end: new Date(2025, 9, 3, 12, 0),
  },
  {
    id: 20,
    title: "History - Geography",
    subject: "History",
    teacher: "Jay French",
    class: "5A",
    room: "Room 103",
    allDay: false,
    start: new Date(2025, 9, 4, 14, 0),
    end: new Date(2025, 9, 4, 15, 0),
  },
  {
    id: 21,
    title: "Math - Calculus",
    subject: "Math",
    teacher: "John Doe",
    class: "5A",
    room: "Room 101",
    allDay: false,
    start: new Date(2025, 9, 4, 8, 0),
    end: new Date(2025, 9, 4, 9, 0),
  },
  {
    id: 22,
    title: "English - Essay Writing",
    subject: "English",
    teacher: "Jane Smith",
    class: "5A",
    room: "Room 102",
    allDay: false,
    start: new Date(2025, 9, 4, 9, 0),
    end: new Date(2025, 9, 4, 10, 0),
  },
  {
    id: 23,
    title: "Physics - Optics",
    subject: "Physics",
    teacher: "Allen Black",
    class: "5A",
    room: "Lab 203",
    allDay: false,
    start: new Date(2025, 9, 4, 11, 0),
    end: new Date(2025, 9, 4, 12, 0),
  },
];